apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-customer-pod
  namespace: wsi
spec:
  podSelector:
    matchLabels:
      app: customer
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: product
