apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    k8s-app: fluent-bit
  name: fluent-bit-config
  namespace: default
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    @INCLUDE input-kubernetes.conf
    @INCLUDE input-order-kubernetes.conf
    @INCLUDE input-product-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-opensearch.conf
    @INCLUDE output-order-opensearch.conf
    @INCLUDE output-product-opensearch.conf

  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.customer.*
        Path              /var/log/containers/customer*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10

  input-order-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.order.*
        Path              /var/log/containers/order*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10

  input-product-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.order.*
        Path              /var/log/containers/product*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10

  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On

  output-opensearch.conf: |
    [OUTPUT]
        Name            es
        Match           kube.customer.*
        Host            ${OPENSEARCH_ENDPOINT}
        Port            443
        TLS             On
        AWS_Auth        On
        AWS_Region      ${AWS_REGION}
        Index           ${CUSTOMER_INDEX_NAME}
        Replace_Dots    On
        Suppress_Type_Name On

  output-order-opensearch.conf: |
    [OUTPUT]
        Name            es
        Match           kube.order.*
        Host            ${OPENSEARCH_ENDPOINT}
        Port            443
        TLS             On
        AWS_Auth        On
        AWS_Region      ${AWS_REGION}
        Index           ${ORDER_INDEX_NAME}
        Replace_Dots    On
        Suppress_Type_Name On

  output-product-opensearch.conf: |
    [OUTPUT]
        Name            es
        Match           kube.order.*
        Host            ${OPENSEARCH_ENDPOINT}
        Port            443
        TLS             On
        AWS_Auth        On
        AWS_Region      ${AWS_REGION}
        Index           ${PRODUCT_INDEX_NAME}
        Replace_Dots    On
        Suppress_Type_Name On

  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
