apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: employee-hpa
  namespace: apdev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: employee-deployment
  minReplicas: 2
  maxReplicas: 20
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Pods
          value: 2
          periodSeconds: 5
    scaleDown:
      stabilizationWindowSeconds: 10
      policies:
        - type: Pods
          value: 1
          periodSeconds: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageValue: 65Mi
