apiVersion: apps/v1
kind: Deployment
metadata:
  name: token-deployment
  namespace: apdev
  labels:
    app: token
spec:
  replicas: 2
  selector:
    matchLabels:
      app: token
  template:
    metadata:
      labels:
        app: token
        apps: worker
    spec:
      containers:
      - name: token-cnt
        image: IMAGE
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
            memory: 300Mi
          requests:
            cpu: 150m
            memory: 150Mi
        startupProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 12
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 6
          successThreshold: 1
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh","-c","sleep 30"]
      terminationGracePeriodSeconds: 10