apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-deployment
  namespace: apdev
  labels:
    app: employee
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
        - name: employee-cnt
          image: IMAGE
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 200m
              memory: 300Mi
            requests:
              cpu: 150m
              memory: 150Mi
          env:
            - name: MYSQL_USER
              value: "dbusername"
            - name: MYSQL_PASSWORD
              value: "dbpassword"
            - name: MYSQL_HOST
              value: "dbhost"
            - name: MYSQL_PORT
              value: "dbport"
            - name: MYSQL_DBNAME
              value: "dbname"
