apiVersion: v1
kind: Service
metadata:
  name: employee-service
  namespace: apdev
spec:
  selector:
    app: employee
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
