apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: apdnodepool
  namespace: app
spec:
  disruption:
    consolidateAfter: 30s
    consolidationPolicy: WhenEmpty
    expireAfter: 2h
  template:
    metadata:
        labels:
         karpenter-node: this
    spec:
      nodeClassRef:
        name: apdnodeclass
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["t3.micro"]

---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: apdnodeclass
  namespace: app
spec:
  tags:
    Name: apdev-app-ng
  amiFamily: Bottlerocket
  role: karpenterNodeRole-apdev-eks-cluster
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: apdev-eks-cluster
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: apdev-eks-cluster
  tags:
    intent: apps
    managed-by: karpenter
  amiSelectorTerms:
    - id: ami-074e925cf02f4ca37