apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: order-secret
  namespace: wsi
spec:
  refreshInterval: 24m
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: order-credentials
    creationPolicy: Owner
  data:
    - secretKey: REGION
      remoteRef:
        key: order
        property: aws_region
