apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: app
  labels:
    app: product
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product-cnt
          image: IMAGE
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: MYSQL_PASSWORD
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: MYSQL_PORT
            - name: MYSQL_DBNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: MYSQL_DBNAME
      nodeSelector:
        skills: app
